### ISSUE TITLE
[PC-Chrome-1920-포트폴리오 메인 페이지] 포트폴리오 삭제 시 포트폴리오 조회 API 오류 

### ISSUE THREAD

**Issue by lucy726j** [100-hours-a-week/5-team-HRTH-ustock-be#127]
##  버그 설명

포트폴리오를 삭제하면 'v1/portfolio' API 500에러,
"Refresh 토큰이 유효하지 않습니다."라는 오류가 뜹니다

로그인 직후에도 해당 오류가 뜨고,
동일한 API를 사용하는 다른 페이지에서는 응답이 잘 옵니다.

## 재현하는 방법

동작을 재현하는 단계:
1. 포트폴리오 삭제 버튼을 누른다.
2. 에러 페이지로 리다이랙션 된다.

## 예상한 동작

1. 포트폴리오가 0이 되면 포트폴리오 추가 안내 페이지로 이동
2. 포트폴리오가 1개 이상이면 포트폴리오 목록 조회 페이지로 이동

## 스크린샷 (옵션)

<img width="1226" alt="스크린샷 2024-09-02 오후 8 50 52" src="https://github.com/user-attachments/assets/a70c7d60-6014-416a-94b2-d54950e52962">

## 데스크톱(다음 정보를 작성해 주세요):
브라우저 : 크롬

**Comment by Lcrescent3es** [comment]
JWTFilter 전역 예외처리 과정에서 발생한 오류로, main 브랜치의 코드로 복구하였습니다.
