### ISSUE TITLE
[기기-브라우저-1920-페이지명] 수익금, 수익률 변수명 변경하기

### ISSUE THREAD

**Issue by sngbmYu** [100-hours-a-week/5-team-HRTH-ustock-be#141]
##  버그 설명

버그에 대한 명확하고 간결한 설명해주세요.

- 수익금, 수익률 변수명이 너무 모호함, 추후 더 명확한 변수명으로 변경 (proceed?)

## 재현하는 방법

동작을 재현하는 단계:

## 예상한 동작

예상했던 일에 대한 명확하고 간결한 설명해주세요.

- 예상동작 1
- 예상동작 2

## 스크린샷 (옵션)

문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.

## 데스크톱(다음 정보를 작성해 주세요):

- OS: [예) iOS]
- Browser [예) chrome, safari]
- Version [예) 22]

## 추가적인 내용 (옵션):

여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by Lcrescent3es** [comment]
ror은 두고, 먼저 수익금만 변경하겠습니다

**Comment by Lcrescent3es** [comment]
> ror은 두고, 먼저 수익금만 변경하겠습니다

반영 완료, develop branch에 push 했습니다 @sngbmYu

**Comment by Lcrescent3es** [comment]
> > ror은 두고, 먼저 수익금만 변경하겠습니다
> 
> 반영 완료, develop branch에 push 했습니다 @sngbmYu

수익금 : profit / 수익률 : profitRate로 변경, 프론트엔드 반영 필요하니 전달하겠습니다(반영되면 issue close할 예정)
