### ISSUE TITLE
[PC-Chrome-1920-포트폴리오 자산 추가 모달] 유효성 범위 안에 있는 수량, 금액 불가

### ISSUE THREAD

**Issue by lucy726j** [100-hours-a-week/5-team-HRTH-ustock-be#86]
##  버그 설명

유효성 범위 안에 있는 수량, 금액 불가합니다.
수량 : 99,999개
금액 : 9,999,999,999원

## 재현하는 방법

동작을 재현하는 단계:

1. 자산 내역을 연다
2. 자산 추가 버튼을 누른다
3. 범위 안에 있지만 큰 숫자를 입력한다
  예시 11,111개 1,111,111,111원

## 예상한 동작
계산이 된다

## 스크린샷 (옵션)

<img width="1270" alt="스크린샷 2024-08-27 오후 2 54 23" src="https://github.com/user-attachments/assets/d5406292-bff2-4788-bb96-8429e457c734">

## 데스크톱(다음 정보를 작성해 주세요):

브라우저 : 크롬

## 추가적인 내용 (옵션):

여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by Lcrescent3es** [comment]
검증식 갯수*구매가 < 999,999,999 -> 구매가 < 9,999,999,999 로 변경했습니다 - 해결
