### ISSUE TITLE
[기기-브라우저-1920-홈 화면 페이지] 로그인 안한 유저한테 오늘의 인기 종목 리스트가 안 보임 

### ISSUE THREAD

**Issue by lucy726j** [100-hours-a-week/5-team-HRTH-ustock-be#91]
##  버그 설명

로그인 안 하면 홈 화면에 있는 인기 종목 리스트가 안뜹니다

## 재현하는 방법

1. 홈 화면에 접속한다

## 예상한 동작

오늘의 인기 종목이 보인다

## 스크린샷 (옵션)

<img width="1510" alt="스크린샷 2024-08-27 오후 9 42 22" src="https://github.com/user-attachments/assets/4541673b-8f98-4472-8b28-b23e9f9ab5e3">

## 데스크톱(다음 정보를 작성해 주세요):

브라우저 : 크롬

## 추가적인 내용 (옵션):

여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by Lcrescent3es** [comment]
현재 발생하지 않는 이슈로, close 하겠습니다
